language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
env:
  global:
    - COMPOSER_FLAGS=""
  matrix:
    - LARAVEL=5.5.*
    - LARAVEL=5.6.*
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=6.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.5.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.6.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.7.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=5.8.*
    - COMPOSER_FLAGS="--prefer-lowest" LARAVEL=6*
matrix:
  exclude:
  - php: 7.1
    env: LARAVEL=^6.0
  allow_failures:
    - php: 7.4snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
